### ISSUE TITLE
Compare different `get` options

### ISSUE THREAD

**Issue by milesfrain** [JordanMartinez/purescript-halogen-hooks-extra#8] opened 2020-07-08 21:07 UTC
```purs
count1 /\ countIdx <- HK.useState 42
count2 <- HK.get countIdx
getCount <- useGet 42
count3 <- getCount

logShow [count1, count2, count3]
```

I'm assuming `count1` and `count2` are equivalent, but `count3` is more up-to-date in some situations.

**Comment by thomashoneyman** [comment] 2020-07-08 22:29
`useGet` is only needed in a certain circumstance: when a function is defined in one Hooks evaluation but is run in another, and it uses a state value. Most commonly this happens when you define an effect with a finalizer: the finalizer is defined in one evaluation, and then it is run in the next evaluation. If that finalizer refers to a state value (like `count1`) then when it executes it will be using the state value from the _previous_ Hooks evaluation.

`useGet` isn't necessary (or advised) for situations like this. It's better to just use `Hooks.get countId ...` instead if you need to use fresh state (state from the current evaluation, not the evaluation in which the finalizer was defined). That's because it's already built in to Halogen and carries no additional overhead (compared to `useGet`, which copies the state into a ref on each evaluation).

It _is_ necessary to use `useGet` if you need to use fresh component input, as there's no `Hooks.get` for component input. In that case you need to copy component input into a mutable reference, which is what `useGet` does.

Edit: `HK.get` as used in the code snippet above won't work -- that's code that has to run in `HookM`, but it's being used in the body of a Hook here instead. Instead, you'd have something like:

```purs
count1 /\ countId <- HK.useState 42

let
  getState :: HookM m Int
  getState = HK.get countId

...
```

**Comment by JordanMartinez** [comment] 2020-07-09 03:30
So... Is this a question? I don't feel like this is a real issue and am tempted to close, but thought I'd clarify first.

**Comment by milesfrain** [comment] 2020-07-09 03:57
I'm wondering if a good follow-up would be to document this a bit more thoroughly.

One issue I just found is that `count1` and `HK.get countIdx` cannot be used interchangeably (for example within some `let` blocks) because `count1` becomes stale. This may be a closure issue.

But this could also be closed now that this discussion is searchable.

**Comment by thomashoneyman** [comment] 2020-07-09 13:16
What case are you seeing the value get stale? In a let binding it should be redefined on each evaluation, so that shouldn’t get stale.

**Comment by milesfrain** [comment] 2020-07-09 18:16
> In a let binding it should be redefined on each evaluation, so that shouldn’t get stale.

Ran a quick experiment, and that's true.
https://try.purescript.org/?gist=69b5a6ae65663d2f5fab20120684745e

So there's some other unknown cause of the stale values I'm seeing.

Here's a specific example:
```purs
      doSaveGist gh_token = do
        -- Cannot just use `content` - will be stale
        currentContent <- HK.get contentIdx
        log $ "saving gist, content: " <> show currentContent
        log $ "example of stale content: " <> show content
```
https://github.com/milesfrain/tps-save-gist/blob/81272301d3552058a8c2aaf6f989abe95f69bba5/src/TPS.purs#L60-L64

`content` contains an empty string (initialization value), but `HK.get contentIdx` produces the correct "Something to save" value.

![image](https://user-images.githubusercontent.com/3578681/87074531-d9873b00-c1d3-11ea-8f99-b2b250e0a106.png)

Also not sure what that memory warning is all about. I assume it's related to the ACE editor.

**Comment by JordanMartinez** [comment] 2020-07-09 19:35
I'm going to close this since it's not an actionable issue and is more of a question/discussion. Feel free to keep discussing though.

**Closed as completed by JordanMartinez** 2020-07-09 19:35 UTC

**Comment by thomashoneyman** [comment] 2020-07-09 19:36
The problem here isn't Hooks-specific; it applies to any Halogen code that modifies state. The `doSaveGist` function is fine but the way it's used is problematic. This example is a nice demonstration of why my description of when you might hit stale state is incomplete.

In Hooks, and in Halogen, if you `get` a state value, then modify the state, the state value you received from `get` is still the old one. For example:

```purs
do
  st <- H.get -- say state is 0 here
  H.put (st + 1)
  when (st > 0) do
    ... -- this code will not run, because `st` is still 0 despite the `put`
```

Halogen will re-render after the call to `put`, but it won't update the `st` variable; it's not a mutable variable, after all. (This is a good thing!) So `st` still points to the value you first received from `get`. The same thing is true in Hooks:

```purs
st /\ id <- useState 0

... do
  Hooks.put id (st + 1)
  when (st > 0) do
    ... -- this code will not run on the first Hooks evaluation, because `st` is still 0
```

Hooks will evaluate again after the call to `put`, but as your code continues executing it will still be referring to the `st` that existed when it started executing.

So my answer was incomplete before when I said that a function only needs to use `get` if it is not executed in the same Hooks evaluation in which it was defined. You also need to remember that it's not a mutable variable, so if you write some code that modifies the state and then uses another stateful function that you either a) need to use `get` or b) pass through the modified state.

Here's a snippet from your linked file:

```purs
    -- Handle routing queries
    HK.useQuery queryToken \(Nav rt a) -> do
      -- multiple state modifications, but not a performance issue now.
      putRoute $ Just rt
      case rt of
        AuthorizeCallback authCode compressed -> do
          log "in auth callback"
          -- Immediately show new content.
          -- This also requires setting saving flag again, since state
          -- is reset upon page refresh from callback.
          writeContent $ decompress compressed
          putGistID SavingGist
          -- Make ghToken request to private app server
          res <- liftAff $ ghRequestToken authCode
          case res of
            Left err -> log err
            Right gh_token -> do
              -- Save ghToken
              putGhToken $ Just gh_token
              -- Save gist
              doSaveGist gh_token
```

This code first calls `writeContent $ decompress compressed`, then calls `doSaveGist gh_token`, which internally refers to the `content` state value. The problem is that `writeContent` modified the state, but `doSaveGist` is then called still pointing at the state that existed when it was defined. What you really need to do is either:

1. Have `writeContent` return the new state, which you pass to `doSaveGist`
2. Have `doSaveGist` call `get` internally

It's kind of like you had:

```purs
handleAction = case _ of
  DoSaveGist compressed -> do
    content <- H.get
    
    -- writeContent
    let content' = decompress compressed
    H.put content'

    (liftAff $ ghRequestToken authCode) >>= traverse_ \gh_token -> do
      saveGist gh_token content -- oops! referring to the old content
```

**Comment by thomashoneyman** [comment] 2020-07-09 19:42
As a brief followup: if you are going to have these state-modifying functions intermixed and it won't be immediately obvious whether or not one of them is at risk of being used after another state-modifying function that interferes with it, then I'd just use `get` in each one. It doesn't hurt anything and it saves you from a potentially time-consuming bug.

I find that most Hooks code I write uses few states and it's rare to update the state more than once in the same handler, so usually this isn't a problem, but in the code you're writing here it is probably safer to just use `get` in these functions and only use the state value returned by `useState` in your render function.
